// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLdIIGmS8UtDLluYi7ACsjEdO1aIFaZIg',
    appId: '1:458497466999:web:5cacfb7217794d9c029c72',
    messagingSenderId: '458497466999',
    projectId: 'chess-e38ed',
    authDomain: 'chess-e38ed.firebaseapp.com',
    databaseURL: 'https://chess-e38ed-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chess-e38ed.appspot.com',
    measurementId: 'G-PWMTL8CRDV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIjL7mXSmCFW_iBBg9BspIu_08oUWTIuc',
    appId: '1:458497466999:android:c87d181176d40f12029c72',
    messagingSenderId: '458497466999',
    projectId: 'chess-e38ed',
    databaseURL: 'https://chess-e38ed-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chess-e38ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoMSDKIEA8--5-wCw1JhJT0ZFksji2Eb0',
    appId: '1:458497466999:ios:e7efa8d5089ded40029c72',
    messagingSenderId: '458497466999',
    projectId: 'chess-e38ed',
    databaseURL: 'https://chess-e38ed-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chess-e38ed.appspot.com',
    iosClientId: '458497466999-67fl49ru1ul66i6rsh87dftuvv58bqir.apps.googleusercontent.com',
    iosBundleId: 'com.example.chessAah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoMSDKIEA8--5-wCw1JhJT0ZFksji2Eb0',
    appId: '1:458497466999:ios:8cd3e2f49542ccbd029c72',
    messagingSenderId: '458497466999',
    projectId: 'chess-e38ed',
    databaseURL: 'https://chess-e38ed-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chess-e38ed.appspot.com',
    iosClientId: '458497466999-1o2v4th0n96of40d39ngc6amu58fob9c.apps.googleusercontent.com',
    iosBundleId: 'com.example.chessAah.RunnerTests',
  );
}
